name = "barc-stage"
pages_build_output_dir = "public"
compatibility_date = "2026-10-01"

[[d1_databases]]
binding = "DB"
database_name = "barc-stage-db"
database_id = "5f62bd2a-a027-4656-b0e5-99bd4286c877"
